Repository Kernel360/KFE3_e2e_n-much, pull requests merged in 2025-07, with the labels that each got.

#71 [feat] - storybook 추가
  .vscode/settings.json
  apps/docs/.storybook/main.ts
  apps/docs/stories/components/ConfirmDialog.stories.tsx
  apps/docs/stories/components/atoms/Badge.stories.tsx
  apps/docs/stories/components/atoms/Button.stories.tsx
  apps/web/src/app/(with-local-layout)/mypage/episodes/page.tsx
Labels: ✨feature

#74 Feature/navbar role #70
  apps/web/src/app/(with-global-layout)/auth/signin/page.tsx
  apps/web/src/app/(with-global-layout)/auth/signup/page.tsx
  apps/web/src/components/layout/TabBar.tsx
  apps/web/src/components/layout/TabNavigation.tsx
  apps/web/src/constants/main/index.tsx
  apps/web/src/lib/supabase/query/auth.ts
  apps/web/src/store/UserStore.ts
Labels: ✨feature

#82 [Style] 수정 등록 페이지 기능 및 UI 재구성
  apps/web/src/app/(with-global-layout)/episode/[...id]/error.tsx
  apps/web/src/app/(with-global-layout)/episode/[...id]/page.tsx
  apps/web/src/app/(with-local-layout)/auctions/[id]/error.tsx
  apps/web/src/app/globals.css
  apps/web/src/components/auctions/detail/AuctionTimer.tsx
  apps/web/src/components/common/AuctionCard.tsx
  apps/web/src/components/common/UserAvatar.tsx
  apps/web/src/components/episodes/EpisodesAuctionCard.tsx
  apps/web/src/components/episodes/EpisodesForm.tsx
  apps/web/src/constants/episodes/index.ts
  apps/web/src/types/auctions/detail/index.ts
  packages/ui/src/components/ui/input.tsx
Labels: 🎨 style, ✍️ refactor

#84 refactor: 인트로 페이지 및 Header, TabBar 기능 수정
  apps/web/src/app/(with-global-layout)/page.tsx
  apps/web/src/components/layout/Header.tsx
  apps/web/src/components/layout/TabNavigation.tsx
  apps/web/src/components/mypage/shared/main/UserProfileCard.tsx
  apps/web/src/constants/main/index.tsx
Labels: ✍️ refactor

#87 Feature/adding additional feature #60
  apps/web/.gitignore
  apps/web/assets/images/noAuctionImage.png
  apps/web/package.json
  apps/web/src/app/(with-global-layout)/auctions/write/page.tsx
  apps/web/src/app/(with-global-layout)/auth/layout.tsx
  apps/web/src/app/(with-global-layout)/auth/signin/page.tsx
  apps/web/src/app/(with-global-layout)/auth/signup/page.tsx
  apps/web/src/app/(with-local-layout)/(with-header-layout)/auctions/page.tsx
  apps/web/src/app/api/auctions_with_episode_count/route.ts
  apps/web/src/components/auctions/AuctionForm.tsx
  apps/web/src/components/auctions/AuctionList.tsx
  apps/web/src/components/auctions/ImageUploader.tsx
  apps/web/src/components/auctions/SelectOrder.tsx
  apps/web/src/components/auth/AuthCard.tsx
  apps/web/src/components/auth/LoadingSpinner.tsx
  apps/web/src/components/common/AuctionCard.tsx
  apps/web/src/hooks/usePopularKeywords.ts
  apps/web/src/hooks/useRecentKeywords.ts
  apps/web/src/lib/queries/auctions.ts
  apps/web/src/lib/supabase/query/auctions.ts
  apps/web/src/providers/QueryProvider.tsx
  apps/web/src/store/AuctionsStore.ts
  apps/web/src/store/UserStore.ts
  packages/ui/src/components/ui/tabs.tsx
  pnpm-lock.yaml
Labels: ✨feature

#89 episode modal UI 변경 및 소셜 닉네임 적용
  apps/web/assets/images/test.png
  apps/web/src/app/(with-local-layout)/auctions/[id]/page.tsx
  apps/web/src/components/auctions/detail/AuctionTimer.tsx
  apps/web/src/components/auctions/detail/EpisodeItem.tsx
  apps/web/src/components/auctions/detail/EpisodeMoreButton.tsx
  apps/web/src/components/auctions/detail/HighestBuyerInfoSection.tsx
  apps/web/src/components/auctions/detail/SellerInfoSection.tsx
Labels: 🎨 style

#90 Bug fix/fixing bugs in adding auction page #88
  apps/web/src/app/(with-global-layout)/auctions/write/page.tsx
  apps/web/src/components/auctions/AuctionForm.tsx
  apps/web/src/components/auctions/ImageUploader.tsx
  apps/web/src/lib/supabase/query/bucket.ts
Labels: 🐞bugfix

#94 [setting] - README.md
  README.md
Labels: ⚙ setting

#95 README.md 업데이트
  README.md
Labels: 📃 docs

#108 move: FSD 구조에 맞게 파일 이동 (#107)
  apps/web/src/app/(with-local-layout)/(with-header-layout)/auctions/page.tsx
  apps/web/src/features/auction/AuctionList.tsx
  apps/web/src/features/auction/shared/AuctionCard.tsx
Labels: ✍️ refactor

#116 Refactor/search #113
  apps/web/src/entities/search/api.ts
  apps/web/src/entities/search/hooks/usePopularKeywords.ts
  apps/web/src/entities/search/hooks/useRecentKeywords.ts
  apps/web/src/entities/search/hooks/useSearchAction.ts
  apps/web/src/entities/search/supabase.ts
  apps/web/src/entities/search/types.ts
  apps/web/src/features/search/BottomDrawer.tsx
  apps/web/src/features/search/PopularKeywords.tsx
  apps/web/src/features/search/RecentKeywords.tsx
  apps/web/src/features/search/SearchBar.tsx
  apps/web/src/features/search/SearchDrawer.tsx
  apps/web/src/features/search/SearchInput.tsx
  apps/web/src/features/search/SearchView.tsx
  packages/ui/package.json
  packages/ui/src/components/ui/drawer.tsx
  pnpm-lock.yaml
Labels: ✍️ refactor

#117 feat: 로그인 인증 로직 추가 (#111)
  apps/web/src/app/(providers)/AppProvider.tsx
  apps/web/src/app/(providers)/AuthProvider.tsx
  apps/web/src/app/(providers)/Providers.tsx
  apps/web/src/app/(with-local-layout)/(with-header-layout)/layout.tsx
  apps/web/src/app/(with-local-layout)/layout.tsx
  apps/web/src/entities/notification/type.ts
  apps/web/src/entities/user/auth/hooks/useAuth.ts
  apps/web/src/features/notification/NotificationButton.tsx
  apps/web/src/features/notification/NotificationList.tsx
  apps/web/src/features/notification/NotificationPopover.tsx
  apps/web/src/features/user/auth/AuthCallbackPage.tsx
  apps/web/src/shared/hooks/useAuthContext.ts
  apps/web/src/shared/ui/AuthWrapper.tsx
  apps/web/src/widgets/LabelBadge.tsx
  apps/web/src/widgets/PageHeader.tsx
  apps/web/src/widgets/layout/Header.tsx
Labels: ✍️ refactor

#125 refactor: 로그인 상태관리 로직
  apps/web/src/app/(providers)/AppProvider.tsx
  apps/web/src/app/(providers)/AuthProvider.tsx
  apps/web/src/app/(providers)/Providers.tsx
  apps/web/src/app/(with-global-layout)/auth/callback/page.tsx
  apps/web/src/app/(with-global-layout)/auth/signup/page.tsx
  apps/web/src/app/(with-local-layout)/auctions/[id]/page.tsx
  apps/web/src/app/api/auctions/route.ts
  apps/web/src/app/api/episodes/route.ts
  apps/web/src/entities/auction/serverActions.ts
  apps/web/src/entities/auth/metaData.ts
  apps/web/src/entities/auth/serverAction.ts
  apps/web/src/entities/auth/stores/authStore.ts
  apps/web/src/entities/auth/supabase.ts
  apps/web/src/entities/auth/types.ts
  apps/web/src/entities/user/auth/hooks/useAuth.ts
  apps/web/src/features/auth/AuthCallbackPage.tsx
  apps/web/src/features/auth/SignUpPage.tsx
  apps/web/src/features/auth/components/SocialAuthButton.tsx
  apps/web/src/features/auth/components/SocialAuthSignUp.tsx
  apps/web/src/features/episode/EpisodePage.tsx
  apps/web/src/features/user/mypage/MyPageMain.tsx
  apps/web/src/features/user/mypage/components/main/MyPageNotification.tsx
  apps/web/src/shared/hooks/useAuthContext.ts
  apps/web/src/shared/supabase/client/server.ts
  apps/web/src/shared/ui/AuthWrapper.tsx
Labels: ✍️ refactor

#129 [Accessibillity] matadata_insert - #127
  apps/web/src/assets/images/mascot.webp
  apps/web/src/entities/layout/metaData.ts
Labels: 🥰 accessibility

#130 Feature/search popular #114
  apps/web/src/app/api/keywords/route.ts
  apps/web/src/entities/auction/constants.ts
  apps/web/src/entities/search/api.ts
  apps/web/src/entities/search/constants.ts
  apps/web/src/entities/search/hooks/usePopularKeywords.ts
  apps/web/src/entities/search/hooks/usePostKeywordMutation.ts
  apps/web/src/entities/search/hooks/useRecentKeywords.ts
  apps/web/src/entities/search/hooks/useSearchAction.ts
  apps/web/src/entities/search/supabase.ts
  apps/web/src/features/search/SearchDrawer.tsx
  apps/web/src/features/search/components/BottomDrawer.tsx
  apps/web/src/features/search/components/PopularKeywords.tsx
  apps/web/src/features/search/components/PopularKeywordsSkeleton.tsx
  apps/web/src/features/search/components/RecentKeywords.tsx
  apps/web/src/features/search/components/SearchInput.tsx
  apps/web/src/features/search/components/SearchView.tsx
  apps/web/src/shared/utils/LocalStorageListUtil.ts
  packages/ui/src/components/ui/skeleton.tsx
Labels: ✨feature

#135 경매 상세페이지 1차 리팩토링 진행 #134
  .vscode/settings.json
  apps/web/src/app/(with-local-layout)/auctions/[id]/page.tsx
  apps/web/src/app/api/auctions/[id]/route.ts
  apps/web/src/app/api/episodes/route.ts
  apps/web/src/assets/images/mascot.webp
  apps/web/src/entities/auction/api.ts
  apps/web/src/entities/auction/serverActions.ts
  apps/web/src/entities/auction/supabase.ts
  apps/web/src/entities/auction/types.ts
  apps/web/src/entities/episode/api.ts
  apps/web/src/features/auction/AuctionDetail.tsx
  apps/web/src/features/auction/AuctionDetailNavbar.tsx
  apps/web/src/features/auction/AuctionTimerDynamic.tsx
  apps/web/src/features/auction/AuctionTimerStatic.tsx
  apps/web/src/features/auction/EndingSoonListSection.tsx
  apps/web/src/features/auction/LatestAuctionCard.tsx
  apps/web/src/features/auction/LatestListSection.tsx
  apps/web/src/features/auction/PopularAuctionCard.tsx
  apps/web/src/features/auction/PopularListSection.tsx
  apps/web/src/features/auction/SellerInfoSection.tsx
  apps/web/src/features/auction/shared/AuctionTimer.tsx
  apps/web/src/features/episode/EpisodeAuctionCard.tsx
  apps/web/src/features/episode/EpisodeForm.tsx
  apps/web/src/features/episode/EpisodePage.tsx
  apps/web/src/shared/supabase/types/supabase.ts
  apps/web/src/shared/ui/BaseBadge.tsx
  apps/web/src/shared/ui/FormDescription.tsx
  apps/web/src/shared/ui/FormTitle.tsx
  apps/web/src/shared/utils/formatRemainingTime.ts
Labels: ✍️ refactor

#142 [refactor] - 문의하기 작성 페이지 뼈대 추가
  apps/web/src/app/(with-global-layout)/inquiries/write/page.tsx
  apps/web/src/app/(with-local-layout)/mypage/inquiries/page.tsx
  apps/web/src/entities/auction/api.ts
  apps/web/src/entities/auction/constants.ts
  apps/web/src/features/inquiries/InquiriesPage.tsx
  apps/web/src/features/inquiries/InquiryWritePage.tsx
  apps/web/src/features/inquiries/components/InquiryForm.tsx
  apps/web/src/features/inquiries/components/InquiryList.tsx
  apps/web/src/features/inquiries/components/InquiryListItem.tsx
Labels: 🎨 style

#156 Refactor/auction detail page pagination #146
  apps/web/src/app/(with-local-layout)/(with-header-layout)/push_sample/page.tsx
  apps/web/src/app/(with-local-layout)/layout.tsx
  apps/web/src/app/api/auctions/[id]/route.ts
  apps/web/src/app/api/auctions/buyer/route.ts
  apps/web/src/app/api/auctions/route.ts
  apps/web/src/app/api/auth/route.ts
  apps/web/src/app/api/episodes/bid/route.ts
  apps/web/src/app/api/episodes/route.ts
  apps/web/src/entities/auction/api.ts
  apps/web/src/entities/auction/constants.ts
  apps/web/src/entities/auction/queries/auction.ts
  apps/web/src/entities/auction/supabase.ts
  apps/web/src/entities/auction/types.ts
  apps/web/src/entities/auth/types.ts
  apps/web/src/entities/episode/api.ts
  apps/web/src/entities/episode/constants.ts
  apps/web/src/entities/episode/queries/episode.ts
  apps/web/src/entities/episode/queries/index.md
  apps/web/src/entities/episode/queries/keys/queryKeyFactory.ts
  apps/web/src/entities/episode/schemas.ts
  apps/web/src/entities/episode/stores/usePaginationStore.ts
  apps/web/src/entities/episode/supabase.ts
  apps/web/src/entities/episode/types.ts
  apps/web/src/features/auction/AuctionActionButtons.tsx
  apps/web/src/features/auction/AuctionBookmarkToggle.tsx
  apps/web/src/features/auction/AuctionDetailInfo.tsx
  apps/web/src/features/auction/AuctionDetailNavbar.tsx
  apps/web/src/features/auction/AuctionDetailPage.tsx
  apps/web/src/features/auction/AuctionTimerDynamic.tsx
  apps/web/src/features/auction/AuctionTimerStatic.tsx
  apps/web/src/features/auction/BidderRankingInfoSection.tsx
  apps/web/src/features/auction/BidderRankingList.tsx
  apps/web/src/features/auction/LatestAuctionCard.tsx
  apps/web/src/features/auction/SellerInfoSection.tsx
  apps/web/src/features/episode/EditDeleteEpisodes.tsx
  apps/web/src/features/episode/EpisodeActionButtons.tsx
  apps/web/src/features/episode/EpisodeAuctionCard.tsx
  apps/web/src/features/episode/EpisodeBidButton.tsx
  apps/web/src/features/episode/EpisodeBidModal.tsx
  apps/web/src/features/episode/EpisodeBidModalForm.tsx
  apps/web/src/features/episode/EpisodeDetailSection.tsx
  apps/web/src/features/episode/EpisodeForm.tsx
  apps/web/src/features/episode/EpisodeInfoModal.tsx
  apps/web/src/features/episode/EpisodeItem.tsx
  apps/web/src/features/episode/EpisodeLikeButton.tsx
  apps/web/src/features/episode/EpisodeList.tsx
  apps/web/src/features/episode/EpisodeMoreButton.tsx
  apps/web/src/features/episode/EpisodeWriteButton.tsx
  apps/web/src/features/episode/shared/EpisodeEmpty.tsx
  apps/web/src/shared/supabase/types/index.ts
  apps/web/src/shared/supabase/types/supabase.ts
  apps/web/src/shared/ui/ContentDescription.tsx
  apps/web/src/shared/ui/ContentTitle.tsx
  apps/web/src/shared/ui/MoreButton.tsx
Labels: ✍️ refactor

#159 Refactor/경매 상세페이지 입찰 시스템 재구성 #158
  apps/web/src/app/api/episodes/bid/route.ts
  apps/web/src/entities/auction/queries/auction.ts
  apps/web/src/entities/episode/api.ts
  apps/web/src/entities/episode/constants.ts
  apps/web/src/entities/episode/queries/episode.ts
  apps/web/src/entities/episode/queries/keys/queryKeyFactory.ts
  apps/web/src/entities/episode/schemas.ts
  apps/web/src/entities/episode/supabase.ts
  apps/web/src/features/auction/AuctionBookmarkToggle.tsx
  apps/web/src/features/auction/AuctionDetailInfo.tsx
  apps/web/src/features/auction/AuctionDetailPage.tsx
  apps/web/src/features/auction/BidderRankingInfoSection.tsx
  apps/web/src/features/auction/EndingSoonCarousel.tsx
  apps/web/src/features/auction/LatestAuctionCard.tsx
  apps/web/src/features/episode/EpisodeActionButtons.tsx
  apps/web/src/features/episode/EpisodeAuctionCard.tsx
  apps/web/src/features/episode/EpisodeBidButton.tsx
  apps/web/src/features/episode/EpisodeBidModal.tsx
  apps/web/src/features/episode/EpisodeBidModalForm.tsx
  apps/web/src/features/episode/EpisodeForm.tsx
  apps/web/src/features/episode/EpisodeInfoModal.tsx
  apps/web/src/features/episode/EpisodeItem.tsx
  apps/web/src/features/user/mypage/components/favorites/components/LikedEpisodesContainer.tsx
  apps/web/src/features/user/mypage/components/points/components/PointHistory.tsx
  apps/web/src/shared/supabase/types/supabase.ts
  apps/web/src/shared/ui/ContentDescription.tsx
  apps/web/src/shared/ui/ContentTitle.tsx
  apps/web/src/shared/ui/FormTitle.tsx
  apps/web/src/shared/ui/PageDescription.tsx
  apps/web/src/shared/ui/PageTitle.tsx
  packages/ui/src/components/ui/badge.tsx
Labels: ✍️ refactor

#169 Feature/my page address #132
  .vscode/settings.json
  apps/web/src/app/api/addresses/route.ts
  apps/web/src/entities/addresses/api.ts
  apps/web/src/entities/addresses/queries/keys.ts
  apps/web/src/entities/addresses/queries/useAddresses.ts
  apps/web/src/entities/addresses/supabase.ts
  apps/web/src/features/addresses/components/AddressForm.tsx
  apps/web/src/features/addresses/components/AddressList.tsx
  apps/web/src/features/addresses/components/AddressListItem.tsx
  apps/web/src/features/user/mypage/components/main/AddressStatus.tsx
  apps/web/src/shared/supabase/types/index.ts
Labels: ✨feature

#168 [bugFix] - 경매 등록 버튼 클릭시 경매 등록이 불가능한 유저도 경매 등록이 가능한 문제 수정
  apps/web/src/entities/auction/supabase.ts
  apps/web/src/features/auction/form/components/AuctionForm.tsx
  apps/web/src/features/auction/form/page/AuctionFormPage.tsx
  apps/web/src/features/auction/list/components/AuctionList.tsx
  apps/web/src/middleware.ts
  apps/web/src/shared/supabase/types/supabase.ts
Labels: 🐞bugfix

#167 Feature/mypage favorites #138
  apps/web/src/app/(with-global-layout)/inquiries/[...id]/page.tsx
  apps/web/src/app/api/auctions/favorites/route.ts
  apps/web/src/app/api/episodes/likes/route.ts
  apps/web/src/app/api/inquiries/route.ts
  apps/web/src/app/api/user/auctions/favorites/route.ts
  apps/web/src/app/api/user/episodes/likes/route.ts
  apps/web/src/entities/auction/api.ts
  apps/web/src/entities/auction/types.ts
  apps/web/src/entities/inquiry/api.ts
  apps/web/src/entities/inquiry/constants.ts
  apps/web/src/entities/inquiry/schemas.ts
  apps/web/src/entities/inquiry/supabase.ts
  apps/web/src/entities/inquiry/types.ts
  apps/web/src/entities/user/mypage/auctions/api.ts
  apps/web/src/entities/user/mypage/auctions/queries/keys.ts
  apps/web/src/entities/user/mypage/auctions/queries/useAuctions.ts
  apps/web/src/entities/user/mypage/auctions/supabase.ts
  apps/web/src/entities/user/mypage/episodes/api.ts
  apps/web/src/entities/user/mypage/episodes/constants.ts
  apps/web/src/entities/user/mypage/episodes/supabase.ts
  apps/web/src/features/auction/AuctionBookmarkToggle.tsx
  apps/web/src/features/auction/AuctionDetailNavbar.tsx
  apps/web/src/features/auction/AuctionFavoriteMarkToggle.tsx
  apps/web/src/features/auction/InquiryDrawerTrigger.tsx
  apps/web/src/features/auction/SellerInfoSection.tsx
  apps/web/src/features/episode/EpisodeItem.tsx
  apps/web/src/features/episode/EpisodeLikeButton.tsx
  apps/web/src/features/inquiries/InquiriesPage.tsx
  apps/web/src/features/inquiries/InquiryWritePage.tsx
  apps/web/src/features/inquiries/components/DescriptionWithMoreButton.tsx
  apps/web/src/features/inquiries/components/EditDeleteButton.tsx
  apps/web/src/features/inquiries/components/InquiryDrawer.tsx
  apps/web/src/features/inquiries/components/InquiryForm.tsx
  apps/web/src/features/inquiries/components/InquiryList.tsx
  apps/web/src/features/inquiries/components/InquiryListItem.tsx
  apps/web/src/features/search/SearchDrawer.tsx
  apps/web/src/features/user/mypage/components/favorites/components/AuctionCardClone.tsx
  apps/web/src/features/user/mypage/components/favorites/components/AuctionListClone.tsx
  apps/web/src/features/user/mypage/components/favorites/components/FavoriteAuctionsContainer.tsx
  apps/web/src/features/user/mypage/components/favorites/components/LikedEpisodesContainer.tsx
  apps/web/src/shared/supabase/types/index.ts
  apps/web/src/shared/ui/BottomDrawer.tsx
  apps/web/src/shared/utils/truncateText.ts
Labels: ✨feature

#173 Refactor/mypage favorites #171
  apps/web/src/entities/user/mypage/auctions/supabase.ts
  apps/web/src/entities/user/mypage/episodes/constants.ts
  apps/web/src/features/auction/AuctionDetailNavbar.tsx
  apps/web/src/features/auction/AuctionFavoriteMarkToggle.tsx
  apps/web/src/features/episode/button/EpisodeLikeButton.tsx
  apps/web/src/features/episode/card/EpisodeCard.tsx
  apps/web/src/features/inquiries/InquiriesPage.tsx
  apps/web/src/features/inquiries/components/EditDeleteButton.tsx
  apps/web/src/features/inquiries/components/InquiryForm.tsx
  apps/web/src/features/search/components/SearchView.tsx
  apps/web/src/features/user/mypage/components/favorites/components/FavoriteAuctionCard.tsx
  apps/web/src/features/user/mypage/components/favorites/components/FavoriteAuctionList.tsx
  apps/web/src/features/user/mypage/components/favorites/components/FavoriteAuctionsContainer.tsx
  apps/web/src/features/user/mypage/components/favorites/components/LikedEpisodesContainer.tsx
Labels: ✍️ refactor

#178 Bugfix/ 경매 상세페이지 에러 수정 및 메인 페이지 스타일링 #172
  apps/web/src/entities/auction/supabase.ts
  apps/web/src/features/auction/AuctionDetailInfo.tsx
  apps/web/src/features/auction/AuctionDetailNavbar.tsx
  apps/web/src/features/auction/EndingSoonListSection.tsx
  apps/web/src/features/auction/InquiryDrawerTrigger.tsx
  apps/web/src/features/auction/LatestListSection.tsx
  apps/web/src/features/auction/PopularListSection.tsx
  apps/web/src/features/auction/SellerInfoSection.tsx
  apps/web/src/features/auction/card/LatestAuctionCard.tsx
  apps/web/src/features/auction/carousel/EndingSoonCarousel.tsx
  apps/web/src/features/auction/list/components/BidderRankingList.tsx
  apps/web/src/features/auction/shared/ContentEmpty.tsx
  apps/web/src/features/auction/skeleton/EndingSoonListSectionSkeleton.tsx
  apps/web/src/features/auction/skeleton/LatestListSectionSkeleton.tsx
  apps/web/src/features/auction/skeleton/PopularListSectionSkeleton.tsx
  apps/web/src/features/auction/skeleton/card/AuctionBaseCardSkeleton.tsx
  apps/web/src/features/auction/skeleton/card/AuctionLatestCardSkeleton.tsx
  apps/web/src/features/auction/skeleton/card/AuctionPopularCardSkeleton.tsx
  apps/web/src/features/auction/skeleton/common/AuctionSectionHeaderSkeleton.tsx
  apps/web/src/features/episode/EpisodeDetailSection.tsx
  apps/web/src/features/episode/button/EpisodeLikeButton.tsx
  apps/web/src/features/episode/card/EpisodeCard.tsx
  apps/web/src/features/episode/modal/EpisodeBidModal.tsx
  apps/web/src/features/episode/modal/EpisodeInfoModal.tsx
  apps/web/src/features/inquiries/InquiriesPage.tsx
  apps/web/src/features/layout/main/MainPage.tsx
  apps/web/src/features/user/mypage/components/shared/EmptyState.tsx
  apps/web/src/shared/ui/ClientContainer.tsx
Labels: 🐞bugfix, 🎨 style, ✍️ refactor

#187 1차 테스트 후, 경매 상세페이지 2차 리팩토링 #180
  apps/web/src/entities/auth/supabase/client.ts
  apps/web/src/features/auction/AuctionDetailNavbar.tsx
  apps/web/src/features/auction/BidderRankingInfoSection.tsx
  apps/web/src/features/auction/PopularListSection.tsx
  apps/web/src/features/auction/SellerInfoSection.tsx
  apps/web/src/features/auction/card/LatestAuctionCard.tsx
  apps/web/src/features/auction/carousel/EndingSoonCarousel.tsx
  apps/web/src/features/auction/list/components/BidderRankingList.tsx
  apps/web/src/features/auction/shared/AuctionCard.tsx
  apps/web/src/features/episode/EpisodePage.tsx
  apps/web/src/features/episode/button/EpisodeWriteButton.tsx
  apps/web/src/features/episode/form/EpisodeBidModalForm.tsx
  apps/web/src/features/episode/form/EpisodeForm.tsx
  apps/web/src/features/episode/modal/EpisodeBidModal.tsx
  apps/web/src/features/episode/skeleton/EpisodeCardSkeleton.tsx
  apps/web/src/shared/ui/FormActionButton.tsx
  apps/web/src/shared/ui/GoBackButton.tsx
  apps/web/src/shared/utils/formatRemainingTime.ts
Labels: 🐞bugfix
