Repository Kernel360/KFE3_e2e_n-much, pull requests merged in 2025-06, with the labels that each got.

#6 feat: 전체 레이아웃 기본 설정, 마이페이지 뼈대 추가 #1
  .github/ISSUE_TEMPLATE/custom-issue-template.md
  .github/pull_request_template.md
  .prettierignore
  .prettierrc
  .vscode/settings.json
  apps/docs/.storybook/main.ts
  apps/docs/.storybook/preview.ts
  apps/docs/.storybook/vitest.setup.ts
  apps/docs/app/layout.tsx
  apps/docs/app/page.tsx
  apps/docs/next.config.ts
  apps/docs/stories/Badge.stories.tsx
  apps/docs/vitest.config.ts
  apps/docs/vitest.shims.d.ts
  apps/web/app/auctions/api/route.ts
  apps/web/app/auctions/page.tsx
  apps/web/app/globals.css
  apps/web/app/layout.tsx
  apps/web/app/mypage/page.tsx
  apps/web/app/mypage/points/page.tsx
  apps/web/app/mypage/posts/page.tsx
  apps/web/app/mypage/profile/page.tsx
  apps/web/app/page.tsx
  apps/web/app/stories/api/route.ts
  apps/web/app/supabse-test/page.tsx
  apps/web/app/users/api/route.ts
  apps/web/next.config.ts
  packages/ui/src/components/Badge.tsx
  packages/ui/src/components/card.tsx
  packages/ui/src/components/gradient.tsx
  packages/ui/src/components/layout/PageContainer.tsx
  packages/ui/src/components/turborepo-logo.tsx
  packages/ui/src/components/typography/PageTitle.tsx
  packages/ui/src/components/ui/button.tsx
  packages/ui/src/lib/utils.ts
  packages/ui/src/types/supabase.ts
  packages/ui/src/utils/supabase/client/client.ts
  packages/ui/src/utils/supabase/client/server.ts
  packages/ui/src/utils/supabase/query/auctions.ts
  packages/ui/src/utils/supabase/query/stories.ts
  packages/ui/src/utils/supabase/query/users.ts
Labels: ⚙ setting, 🎨 style

#11 [setting] - 라우트 헨들러 경로 설정
  .gitignore
  apps/docs/.gitignore
  apps/web/.gitignore
  apps/web/app/api/auctions/route.ts
  apps/web/app/api/stories/route.ts
  apps/web/app/api/users/route.ts
Labels: ⚙ setting

#14 feat: auth 폴더 및 signup, signin 구조 구현 (#13)
  apps/web/app/auth/layout.tsx
  apps/web/app/auth/signin/page.tsx
  apps/web/app/auth/signup/page.tsx
Labels: ✨feature

#17 Style/navbar #12
  apps/web/app/layout.tsx
  packages/ui/src/components/navbar/navbar.tsx
  packages/ui/src/types/supabase.ts
  pnpm-lock.yaml
Labels: 🎨 style

#25 Style/header UI #21
  apps/web/app/layout.tsx
  packages/ui/src/components/common/Header.tsx
  pnpm-lock.yaml
Labels: 🎨 style

#34 Feature/signup page #16
  apps/web/assets/logos/google_logo.png
  apps/web/assets/logos/kakao_logo.png
  apps/web/src/app/auctions/[id]/page.tsx
  apps/web/src/app/auth/signup/page.tsx
  apps/web/src/app/episode/[...id]/page.tsx
  apps/web/src/components/auctions/detail/EpisodeItem.tsx
  apps/web/src/components/auth/AuthCard.tsx
  apps/web/src/lib/supabase/query/auth.ts
  apps/web/src/lib/supabase/query/episodes.ts
  apps/web/src/lib/supabase/query/users.ts
  apps/web/src/types/auth/index.ts
  apps/web/src/types/mypage/index.ts
  packages/ui/package.json
  packages/ui/src/components/ui/card.tsx
  packages/ui/src/components/ui/tabs.tsx
  pnpm-lock.yaml
Labels: ✨feature

#44 Feature/signin page #41
  apps/web/src/app/auth/signin/page.tsx
  apps/web/src/app/auth/signup/page.tsx
  apps/web/src/components/auth/LoadingSpinner.tsx
  apps/web/src/components/auth/README.md
  apps/web/src/lib/supabase/query/auth.ts
  apps/web/src/types/supabase.ts
Labels: ✨feature

#48 [feat] - 마이페이지 내 경매 현황 리스트 추가, 공통 컴포넌트 추가
  apps/web/package.json
  apps/web/src/app/layout.tsx
  apps/web/src/app/mypage/auctions/page.tsx
  apps/web/src/app/mypage/page.tsx
  apps/web/src/components/common/GoBackButton.tsx
  apps/web/src/components/common/PageHeader.tsx
  apps/web/src/components/common/TabTriggerItem.tsx
  apps/web/src/components/common/UIButton.tsx
  apps/web/src/components/layout/PageContainer.tsx
  apps/web/src/components/mypage/bidder/BidderMenuList.tsx
  apps/web/src/components/mypage/shared/StatusBadge.tsx
  apps/web/src/components/mypage/shared/auctions/AuctionListItem.tsx
  apps/web/src/components/mypage/shared/auctions/AuctionStatusFilters.tsx
  apps/web/src/components/mypage/shared/auctions/AuctionTabsContent.tsx
  apps/web/src/components/mypage/shared/auctions/AuctionTabsHeader.tsx
  apps/web/src/components/mypage/shared/auctions/AuctionTabsSection.tsx
  apps/web/src/components/mypage/shared/main/ActivityItem.tsx
  apps/web/src/components/mypage/shared/main/ActivityList.tsx
  apps/web/src/components/mypage/shared/main/MyPageMenuList.tsx
  apps/web/src/components/mypage/shared/main/MyPageNotification.tsx
  apps/web/src/components/mypage/shared/main/UserProfileCard.tsx
  apps/web/src/constants/mypage/index.tsx
  apps/web/src/constants/mypage/mockData.ts
  apps/web/src/types/mypage/index.ts
  apps/web/src/utils/mypage/auctionFilters.ts
  pnpm-lock.yaml
Labels: ✨feature

#61 Feature/search feature #50
  apps/web/package.json
  apps/web/src/components/common/SearchBar.tsx
  apps/web/src/hooks/usePopularKeywords.ts
  apps/web/src/hooks/useRecentKeywords.ts
  apps/web/src/lib/supabase/query/auctions.ts
  apps/web/src/store/AuctionsStore.ts
  pnpm-lock.yaml
Labels: ✨feature

#63 메인 페이지 기능 구현
  apps/docs/next.config.ts
  apps/web/assets/images/auctionDefault.png
  apps/web/assets/images/banner_1.png
  apps/web/assets/images/banner_2.png
  apps/web/assets/images/banner_3.png
  apps/web/package.json
  apps/web/src/app/api/auctions/[id]/route.ts
  apps/web/src/app/api/episodes/bid/route.ts
  apps/web/src/app/api/episodes/route.ts
  apps/web/src/app/auctions/[id]/page.tsx
  apps/web/src/app/page.tsx
  apps/web/src/components/auctions/AuctionList.tsx
  apps/web/src/components/auctions/detail/AuctionTimer.tsx
  apps/web/src/components/auctions/detail/EpisodeList.tsx
  apps/web/src/components/common/AuctionCard.tsx
  apps/web/src/components/common/AuctionErrorBoundary.tsx
  apps/web/src/components/main/EndingSoonCarousel.tsx
  apps/web/src/components/main/EndingSoonListSection.tsx
  apps/web/src/components/main/LatestAuctionCard.tsx
  apps/web/src/components/main/LatestListSection.tsx
  apps/web/src/components/main/MainBanner.tsx
  apps/web/src/components/main/PopularAuctionCard.tsx
  apps/web/src/components/main/PopularListSection.tsx
  apps/web/src/constants/main/index.tsx
  apps/web/src/lib/actions/serverActions.ts
  apps/web/src/lib/queries/auctions.ts
  apps/web/src/lib/supabase/query/auctions.ts
  apps/web/src/types/main/index.ts
  packages/ui/package.json
  packages/ui/src/components/ui/carousel.tsx
  packages/ui/src/components/ui/separator.tsx
  packages/ui/src/lib/utils.ts
  pnpm-lock.yaml
Labels: ✨feature

#67 refactor: 헤더 및 TabBar 그룹화
  apps/web/src/app/(with-global-layout)/auctions/write/page.tsx
  apps/web/src/app/(with-global-layout)/auth/layout.tsx
  apps/web/src/app/(with-global-layout)/auth/signin/page.tsx
  apps/web/src/app/(with-global-layout)/auth/signup/page.tsx
  apps/web/src/app/(with-global-layout)/episode/[...id]/page.tsx
  apps/web/src/app/(with-global-layout)/layout.tsx
  apps/web/src/app/(with-global-layout)/page.tsx
  apps/web/src/app/(with-local-layout)/(with-header-layout)/auctions/page.tsx
  apps/web/src/app/(with-local-layout)/(with-header-layout)/layout.tsx
  apps/web/src/app/(with-local-layout)/(with-header-layout)/main/page.tsx
  apps/web/src/app/(with-local-layout)/(with-header-layout)/mypage/episodes/page.tsx
  apps/web/src/app/(with-local-layout)/(with-header-layout)/mypage/page.tsx
  apps/web/src/app/(with-local-layout)/auctions/[id]/error.tsx
  apps/web/src/app/(with-local-layout)/auctions/[id]/page.tsx
  apps/web/src/app/(with-local-layout)/layout.tsx
  apps/web/src/app/(with-local-layout)/mypage/auctions/page.tsx
  apps/web/src/app/(with-local-layout)/mypage/points/page.tsx
  apps/web/src/app/layout.tsx
Labels: ⚙ setting, ✍️ refactor
