Repository Kernel360/KFE3_e2e_n-much, pull requests merged in 2025-08, with the labels that each got.

#192 feature: pwa 1차 적용 및 등록 버튼 조건부 처리 (#188)
  .vscode/settings.json
  apps/web/.gitignore
  apps/web/next.config.ts
  apps/web/package.json
  apps/web/public/OneSignalSDKWorker.js
  apps/web/public/sw.js
  apps/web/public/web_app_manifest_192.png
  apps/web/public/web_app_manifest_512.png
  apps/web/src/app/(with-local-layout)/(with-header-layout)/push_sample/page.tsx
  apps/web/src/app/favicon.ico
  apps/web/src/app/manifest.ts
  apps/web/src/app/pwa/(actions)/actions.ts
  apps/web/src/app/pwa/page.tsx
  apps/web/src/features/auction/list/page/AuctionListPage.tsx
  pnpm-lock.yaml
Labels: ✨feature

#193 Refactor/mypage #185
  apps/web/src/app/(with-local-layout)/auctions/[id]/page.tsx
  apps/web/src/app/globals.css
  apps/web/src/assets/images/logo_dark.svg
  apps/web/src/assets/images/mascot_closed.webp
  apps/web/src/entities/auction/api.ts
  apps/web/src/entities/user/mypage/main/constants.ts
  apps/web/src/features/addresses/components/AddressForm.tsx
  apps/web/src/features/auction/AuctionDetailInfo.tsx
  apps/web/src/features/auction/EndingSoonListSection.tsx
  apps/web/src/features/auction/LatestListSection.tsx
  apps/web/src/features/auction/PopularListSection.tsx
  apps/web/src/features/auction/detail/AuctionDetailPage.tsx
  apps/web/src/features/auction/detail/components/BackButton.tsx
  apps/web/src/features/auction/detail/components/ClosedAuctionOverlay.tsx
  apps/web/src/features/auction/form/components/AuctionForm.tsx
  apps/web/src/features/auction/list/components/AuctionList.tsx
  apps/web/src/features/auction/list/components/BidderRankingList.tsx
  apps/web/src/features/auction/list/page/AuctionListPage.tsx
  apps/web/src/features/auction/timer/AuctionTimerDynamic.tsx
  apps/web/src/features/episode/modal/EpisodeBidModal.tsx
  apps/web/src/features/inquiries/InquiriesPage.tsx
  apps/web/src/features/layout/header/RoleSwitch.tsx
  apps/web/src/features/layout/header/skeleton/RoleSwitchSkeleton.tsx
  apps/web/src/features/layout/main/MainPage.tsx
  apps/web/src/features/layout/nav/MobileNavigationList.tsx
  apps/web/src/features/user/mypage/components/auctions/components/ClosedAuctionsContainer.tsx
  apps/web/src/features/user/mypage/components/auctions/components/MyAuctionsTabContainer.tsx
  apps/web/src/features/user/mypage/components/auctions/components/OpenAuctionsContainer.tsx
  apps/web/src/features/user/mypage/components/auctions/skeleton/AuctionItemSkeleton.tsx
  apps/web/src/features/user/mypage/components/episodes/components/CompletedEpisodesContainer.tsx
  apps/web/src/features/user/mypage/components/episodes/components/MyEpisodesTabContainer.tsx
  apps/web/src/features/user/mypage/components/episodes/components/OngoingEpisodesContainer.tsx
  apps/web/src/features/user/mypage/components/favorites/components/FavoriteAuctionList.tsx
  apps/web/src/features/user/mypage/components/favorites/components/LikedEpisodesContainer.tsx
  apps/web/src/features/user/mypage/components/main/MyPageUserProfile.tsx
  apps/web/src/features/user/mypage/components/main/skeleton/MyPageUserProfileSkeleton.tsx
  apps/web/src/features/user/mypage/components/points/components/PointHistoryList.tsx
  apps/web/src/shared/ui/EmptyState.tsx
  apps/web/src/shared/ui/ErrorState.tsx
  apps/web/src/widgets/layout/Header.tsx
  packages/ui/src/components/ui/input.tsx
  packages/ui/src/components/ui/select.tsx
  packages/ui/src/components/ui/tabs.tsx
  packages/ui/src/components/ui/textarea.tsx
Labels: ✍️ refactor

#197 [feat] - 마이페이지 주소 스켈레톤 처리
  apps/web/src/app/(with-global-layout)/testmodal/page.tsx
  apps/web/src/features/user/mypage/components/main/AddressStatus.tsx
  apps/web/src/features/user/mypage/components/main/skeleton/AddressStatusSkeleton.tsx
Labels: ✨feature

#200 [bugfix] - 로그인 세션 상태 동기화 문제, 입찰참여자, 경매진행자 깜빡임 현상 수정
  .vscode/settings.json
  apps/web/src/app/(providers)/AuthProvider.tsx
  apps/web/src/app/(with-global-layout)/episode/[...id]/error.tsx
  apps/web/src/app/(with-local-layout)/auctions/[id]/error.tsx
  apps/web/src/app/globals.css
  apps/web/src/features/auction/EndingSoonListSection.tsx
  apps/web/src/features/auction/LatestListSection.tsx
  apps/web/src/features/auction/PopularListSection.tsx
  apps/web/src/features/auction/button/WriteAuctionButton.tsx
  apps/web/src/features/auction/list/page/AuctionListPage.tsx
  apps/web/src/features/layout/header/RoleSwitch.tsx
  apps/web/src/features/layout/header/skeleton/RoleSwitchSkeleton.tsx
  apps/web/src/features/search/components/SearchInput.tsx
  apps/web/src/features/user/mypage/components/main/MyPageNavigation.tsx
  apps/web/src/features/user/mypage/components/main/MyPageUserProfile.tsx
  apps/web/src/features/user/mypage/components/main/skeleton/MyPageUserProfileSkeleton.tsx
  apps/web/src/features/user/mypage/components/points/skeleton/PointOverviewSkeleton.tsx
  apps/web/src/features/user/mypage/components/shared/skeleton/TabsSkeleton.tsx
Labels: 🐞bugfix

#210 Bugfix/auction detail page #204
  apps/web/src/app/(with-global-layout)/chat/[id]/page.tsx
  apps/web/src/app/api/send_auction_notifications/route.ts
  apps/web/src/entities/auth/types.ts
  apps/web/src/entities/episode/supabase.ts
  apps/web/src/entities/notification/serverActions.ts
  apps/web/src/features/auction/AuctionDetailInfo.tsx
  apps/web/src/features/auction/AuctionDetailNavbar.tsx
  apps/web/src/features/auction/AuctionFavoriteMarkToggle.tsx
  apps/web/src/features/auction/SellerInfoSection.tsx
  apps/web/src/features/auction/button/AuctionActionButtons.tsx
  apps/web/src/features/auction/timer/AuctionTimerDynamic.tsx
  apps/web/src/features/episode/button/EpisodeLikeButton.tsx
  apps/web/src/features/episode/button/EpisodeWriteButton.tsx
  apps/web/src/features/episode/card/EpisodeCard.tsx
  apps/web/src/features/episode/form/EpisodeBidModalForm.tsx
  apps/web/src/features/episode/list/EpisodeList.tsx
  apps/web/src/features/episode/modal/EpisodeBidModal.tsx
Labels: 🐞bugfix
